import { createConnectQueryKey } from '@connectrpc/connect-query'
import { listPlans } from '@rpc/plan/v1/plan-PlanService_connectquery'

/**
 * Centralized query keys factory (Cosmo pattern).
 * Provides type-safe, consistent query keys across the app.
 *
 * For Connect RPC methods, use `connectQueryKeys` which aligns with
 * connect-query's automatic key generation for SSR/CSR parity.
 */
export const queryKeys = {
  plans: {
    all: ['plans'] as const,
    list: () => [...queryKeys.plans.all, 'list'] as const,
    detail: (id: string) => [...queryKeys.plans.all, 'detail', id] as const,
  },
  users: {
    all: ['users'] as const,
    list: () => [...queryKeys.users.all, 'list'] as const,
    detail: (id: string) => [...queryKeys.users.all, 'detail', id] as const,
    current: () => [...queryKeys.users.all, 'current'] as const,
  },
} as const

/**
 * Connect Query keys for SSR prefetching.
 * These match the keys generated by connect-query hooks automatically.
 *
 * Use these for server-side prefetching to ensure hydration works correctly.
 */
export const connectQueryKeys = {
  plans: {
    /**
     * Query key for listPlans - matches connect-query's useQuery(listPlans, {})
     */
    list: () => createConnectQueryKey(listPlans, {}),
  },
} as const

export type QueryKeys = typeof queryKeys
export type ConnectQueryKeys = typeof connectQueryKeys
